In [1]:
import os
import io
import csv
import pandas as pd
import numpy as np
from tabulate import tabulate
import logging
logging.getLogger().setLevel(logging.INFO)

import psycopg2
conn = psycopg2.connect(user='airflow', password='Xypherium-0',
                        dbname='jpstat',
                        host='35.224.240.50')

In [2]:
pd.set_option('display.max_colwidth', -1)
pd.set_option('display.max_rows', None, 'display.max_columns', None)

In [3]:
path = os.path.join('extracts', 'monthly_reports')

In [ ]:
def get_directory_structure(rootdir):
    """
    Creates a nested dictionary that represents the folder structure of rootdir
    """
    dir = {}
    rootdir = rootdir.rstrip(os.sep)
    start = rootdir.rfind(os.sep) + 1
    for path, dirs, files in os.walk(rootdir):
        folders = path[start:].split(os.sep)
        subdir = dict.fromkeys(files)
        parent = reduce(dict.get, folders[:-1], dir)
        parent[folders[-1]] = subdir
    return dir

In [4]:
filepathlist = []
for dirpath, subdir, files in os.walk(path):
    for filename in files:
        if filename.endswith('.xls'):
            filepathlist.append(os.path.join(dirpath, filename))

In [ ]:
%%time
tableshape_list = []
df_dict = {}
for filepath in filepathlist:
    sheets = pd.ExcelFile(filepath).sheet_names
    
    df = pd.read_excel(filepath, sheet_name=len(sheets)-1)
    filepath_list = filepath.split('\\')
    description = [filepath_list[2] + '-' + filepath_list[3], filepath_list[4], df.shape]
    
    if len(sheets) > 1:
        print(filepath_list[2] + '-' + filepath_list[3] + ' ' + filepath_list[4] + ' has ' + str(len(sheets)) + ' sheets.')
    
    tableshape_list.append(description)

In [ ]:
tableshape_df = pd.DataFrame(tableshape_list, columns=['year-month', 'file', 'shape'])

In [ ]:
tableshape_df.info

In [ ]:
tableshape_agg_df = tableshape_df.groupby(['file', 'shape'])['year-month'].apply(list).reset_index()

In [ ]:
tableshape_agg_df['count'] = [len(x) for x in tableshape_agg_df['year-month']]
[x.sort for x in tableshape_agg_df['year-month']]
tableshape_agg_df.sort_values(by='year-month')
tableshape_agg_df

In [5]:
table_1_list= [x for x in filepathlist if x.split('\\')[-1] == '1.xls']
table3_1_list = [x for x in filepathlist if '3-1' in x]
table3_2_list = [x for x in filepathlist if '3-2' in x]

In [6]:
def combine_clean_1xls_tables(table_excel_list):
    table_df_list = []

    for filepath in table_excel_list:
        filepath_parts = filepath.split('\\')
        year = filepath_parts[2]
        month = filepath_parts[3][:2]

        sheets = pd.ExcelFile(filepath).sheet_names
        df = pd.read_excel(filepath, sheet_name=len(sheets)-1)

        messy_df = df.copy()
        messy_df.reset_index(inplace=True)
        
        cornerstone = '全国'
        cornerstone_col_idx = [messy_df.columns.get_loc(x) for x in messy_df.columns if cornerstone in messy_df[x].values][0]
        cornerstone_col = messy_df.iloc[:,cornerstone_col_idx]
        cornerstone_row_idx = int(cornerstone_col.index[cornerstone_col == cornerstone][0])
        messy_df = messy_df.iloc[:,cornerstone_col_idx:cornerstone_col_idx+6]

        messy_df.columns = ['Prefecture Num', 'Prefecture', 'Prefecture_English', 'Both', 'Male', 'Female']
        messy_df.dropna(axis=0, subset=['Prefecture Num', 'Both', 'Male', 'Female'], how='any', inplace=True)
        
        #using the fact that np.nan != np.nan
        messy_df['Prefecture'] = messy_df.apply(lambda x: x['Prefecture Num'] if x['Prefecture']!=x['Prefecture'] else x['Prefecture'], axis=1)
        messy_df['Prefecture Num'] = messy_df.apply(lambda x: '00' if x['Prefecture Num']=='全国' else x['Prefecture Num'], axis=1)
        messy_df['Prefecture Num'] = messy_df.apply(lambda x: '00 000' if '計' in x['Prefecture Num'] else x['Prefecture Num'], axis=1)
        ku_codes = {
            '東京圏': '100',
            '名古屋圏': '101',
            '大阪圏': '102'
        }
        messy_df['Prefecture Num'] = messy_df.apply(lambda x: ku_codes.get(x['Prefecture Num']) if x['Prefecture Num'] in ku_codes else x['Prefecture Num'], axis=1)
        messy_df['Prefecture_English'] = messy_df.apply(lambda x: x['Prefecture_English'].rstrip(' 3)'), axis=1)
        messy_df['Prefecture_English'] = messy_df.apply(lambda x: x['Prefecture_English'] + ' cities' if 'major' in x['Prefecture_English'] else x['Prefecture_English'], axis=1)
        
        messy_df['Year'] = str(year)
        messy_df['Month'] = str(month)
        messy_df['Age bucket'] = 'Total'

        messy_df = messy_df.reindex(columns=['Prefecture Num', 'Prefecture', 'Prefecture_English', 'Year', 'Month', 'Age bucket', 'Both', 'Male', 'Female'])
        
        if False not in messy_df.iloc[:,7:10].applymap(np.isreal).values.flatten():
            table_df_list.append(messy_df)
        else:
            print('Some non-numeric value found in internal migration counts.')
            print(messy_df.iloc[:,7:10].head(5))

    combined_df = pd.concat(table_df_list).reset_index(drop=True)
    if '大阪圏' in combined_df['Prefecture Num']: print('matched multiple kanji string!')
    return combined_df

In [7]:
def combine_clean_3xls_tables(table_excel_list):
    #Always take the last sheet: assume that in the absense of separate sheets, the numbers are for Japanese citizens only
    table_df_list = []

    for filepath in table_excel_list:
        filepath_parts = filepath.split('\\')
        year = filepath_parts[2]
        month = filepath_parts[3][:2]

        sheets = pd.ExcelFile(filepath).sheet_names
        df = pd.read_excel(filepath, sheet_name=len(sheets)-1)

        messy_df = df.copy()
        messy_df.reset_index(inplace=True)
        messy_df.columns = [x.replace('～', '-') for x in messy_df.iloc[13].replace({
                                                    'Prefectures': 'Prefecture Num',
                                                    '総 数 1)': 'Total',
                                                    '0～4歳': '0～4',
                                                    '90歳以上': '90 & above'
                                                    }).fillna('Prefecture')]
        messy_df.iloc[18,10] = messy_df.iloc[18,8]
        messy_df = messy_df.iloc[18:66,8:]
        messy_df.reset_index(drop=True, inplace=True)
        messy_df.dropna(axis=1, inplace=True)
        messy_df.loc[0,'Prefecture Num'] = '00'

        both_df = messy_df.iloc[:,:22]
        male_df = messy_df.iloc[:,22:44]
        female_df = messy_df.iloc[:,44:66]

        both_df['Gender'] = 'Both'
        male_df['Gender'] = 'Male'
        female_df['Gender'] = 'Female'

        this_month_df = pd.concat([both_df, male_df, female_df])
        this_month_df['Year'] = str(year)
        this_month_df['Month'] = str(month)

        if False not in this_month_df.iloc[:,2:22].applymap(np.isreal).values.flatten():
            table_df_list.append(this_month_df)
        else:
            print('Some non-numeric value found in in/out migration counts.')
    
    combined_df = pd.concat(table_df_list).reset_index(drop=True)
    return combined_df

In [8]:
%%time
in_migrants_age_df = combine_clean_3xls_tables(table3_1_list)
out_migrants_age_df = combine_clean_3xls_tables(table3_2_list)
internal_migrants_df = combine_clean_1xls_tables(table_1_list)

C:\Users\friedemann.ang\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\friedemann.ang\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\friedemann.ang\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\friedemann.ang\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  app.launch_new_instance()

Wall time: 28.1 s

In [9]:
jp2en_df = internal_migrants_df[['Prefecture', 'Prefecture_English']].drop_duplicates()
jp2en_df.set_index('Prefecture', inplace=True)
jp2en_dict = jp2en_df['Prefecture_English'].to_dict()

In [10]:
jp2en_dict.get('北海道')

' Hokkaido'

In [11]:
internal_migrants_df.tail(60)

,Prefecture Num,Prefecture,Prefecture_English,Year,Month,Age bucket,Both,Male,Female
10260,13,東京都,Tokyo-to,2018,06,Total,28529,14549,13980
10261,14,神奈川県,Kanagawa-ken,2018,06,Total,15365,7878,7487
10262,15,新潟県,Niigata-ken,2018,06,Total,2196,1075,1121
10263,16,富山県,Toyama-ken,2018,06,Total,657,316,341
10264,17,石川県,Ishikawa-ken,2018,06,Total,990,474,516
10265,18,福井県,Fukui-ken,2018,06,Total,569,278,291
10266,19,山梨県,Yamanashi-ken,2018,06,Total,974,457,517
10267,20,長野県,Nagano-ken,2018,06,Total,2044,1007,1037
10268,21,岐阜県,Gifu-ken,2018,06,Total,1643,844,799
10269,22,静岡県,Shizuoka-ken,2018,06,Total,4395,2275,2120
10270,23,愛知県,Aichi-ken,2018,06,Total,12819,6859,5960
10271,24,三重県,Mie-ken,2018,06,Total,1467,770,697
10272,25,滋賀県,Shiga-ken,2018,06,Total,1255,656,599
10273,26,京都府,Kyoto-fu,2018,06,Total,3301,1639,1662
10274,27,大阪府,Osaka-fu,2018,06,Total,15480,7894,7586
10275,28,兵庫県,Hyogo-ken,2018,06,Total,6678,3300,3378
10276,29,奈良県,Nara-ken,2018,06,Total,1100,538,562
10277,30,和歌山県,Wakayama-ken,2018,06,Total,712,355,357
10278,31,鳥取県,Tottori-ken,2018,06,Total,355,180,175
10279,32,島根県,Shimane-ken,2018,06,Total,304,148,156
10280,33,岡山県,Okayama-ken,2018,06,Total,2009,998,1011
10281,34,広島県,Hiroshima-ken,2018,06,Total,3636,1867,1769
10282,35,山口県,Yamaguchi-ken,2018,06,Total,995,537,458
10283,36,徳島県,Tokushima-ken,2018,06,Total,642,309,333
10284,37,香川県,Kagawa-ken,2018,06,Total,704,357,347
10285,38,愛媛県,Ehime-ken,2018,06,Total,938,454,484
10286,39,高知県,Kochi-ken,2018,06,Total,677,332,345
10287,40,福岡県,Fukuoka-ken,2018,06,Total,10572,5295,5277
10288,41,佐賀県,Saga-ken,2018,06,Total,678,327,351
10289,42,長崎県,Nagasaki-ken,2018,06,Total,1110,558,552
10290,43,熊本県,Kumamoto-ken,2018,06,Total,3097,1458,1639
10291,44,大分県,Oita-ken,2018,06,Total,912,462,450
10292,45,宮崎県,Miyazaki-ken,2018,06,Total,877,415,462
10293,46,鹿児島県,Kagoshima-ken,2018,06,Total,1571,776,795
10294,47,沖縄県,Okinawa-ken,2018,06,Total,2963,1459,1504
10295,100,東京圏,Tokyo Area,2018,06,Total,93524,48572,44952
10296,101,名古屋圏,Nagoya Area,2018,06,Total,18690,10009,8681
10297,102,大阪圏,Osaka Area,2018,06,Total,34268,17311,16957
10298,00 000,21 大 都 市 計,Total of 21 major cities,2018,06,Total,54671,27456,27215
10299,01 100,札幌市,Sapporo-shi,2018,06,Total,4255,1973,2282
10300,04 100,仙台市,Sendai-shi,2018,06,Total,1494,699,795
10301,11 100,さいたま市,Saitama-shi,2018,06,Total,1343,670,673
10302,12 100,千葉市,Chiba-shi,2018,06,Total,871,453,418
10303,13 100,東京都特別区部,Ku-area of Tokyo,2018,06,Total,18239,9410,8829
10304,14 100,横浜市,Yokohama-shi,2018,06,Total,4965,2458,2507
10305,14 130,川崎市,Kawasaki-shi,2018,06,Total,1265,660,605
10306,14 150,相模原市,Sagamihara-shi,2018,06,Total,404,210,194
10307,15 100,新潟市,Niigata-shi,2018,06,Total,808,382,426
10308,22 100,静岡市,Shizuoka-shi,2018,06,Total,541,273,268
10309,22 130,浜松市,Hamamatsu-shi,2018,06,Total,966,479,487
10310,23 100,名古屋市,Nagoya-shi,2018,06,Total,3628,1876,1752
10311,26 100,京都市,Kyoto-shi,2018,06,Total,1795,871,924
10312,27 100,大阪市,Osaka-shi,2018,06,Total,4560,2347,2213
10313,27 140,堺市,Sakai-shi,2018,06,Total,713,352,361
10314,28 100,神戸市,Kobe-shi,2018,06,Total,1720,836,884
10315,33 100,岡山市,Okayama-shi,2018,06,Total,679,331,348
10316,34 100,広島市,Hiroshima-shi,2018,06,Total,1573,777,796
10317,40 100,北九州市,Kitakyushu-shi,2018,06,Total,1108,560,548
10318,40 130,福岡市,Fukuoka-shi,2018,06,Total,2647,1331,1316
10319,43 100,熊本市,Kumamoto-shi,2018,06,Total,1097,508,589

In [12]:
keys_1xls = ['Both', 'Male', 'Female']
internal_melted_df = pd.melt(internal_migrants_df, 
                             id_vars=['Prefecture Num', 'Prefecture', 'Prefecture_English', 'Year', 'Month', 'Age bucket'], 
                             value_name='Internal migrants', 
                             value_vars=keys_1xls, 
                             var_name='Gender')

In [13]:
len(internal_melted_df)

30960

In [14]:
out_migrants_age_df.head(20)

,Prefecture Num,Prefecture,Total,0-4,5-9,10-14,15-19,20-24,25-29,30-34,35-39,40-44,45-49,50-54,55-59,60-64,65-69,70-74,75-79,80-84,85-89,90 & above,Gender,Year,Month
0,00,全国,126018,7924,3182,1637,3610,20043,26958,20002,13587,7826,4881,3811,3580,3247,1722,1098,946,864,711,387,Both,2010,01
1,01,北海道,2561,136,77,45,103,473,441,365,296,186,112,99,98,47,27,18,11,13,9,5,Both,2010,01
2,02,青森県,1119,66,38,30,34,277,186,152,103,51,47,39,37,22,9,9,4,5,8,2,Both,2010,01
3,03,岩手県,992,74,31,10,37,201,167,155,83,50,59,39,31,23,11,5,6,5,2,3,Both,2010,01
4,04,宮城県,2085,160,59,28,66,372,422,298,242,123,88,74,54,38,17,11,13,9,8,3,Both,2010,01
5,05,秋田県,753,50,24,11,25,176,121,98,71,39,27,23,25,17,14,4,10,11,3,4,Both,2010,01
6,06,山形県,736,43,27,11,35,165,139,99,70,32,22,27,17,21,9,7,3,1,6,2,Both,2010,01
7,07,福島県,1386,87,25,17,48,336,253,186,128,87,57,44,32,23,12,12,7,16,11,5,Both,2010,01
8,08,茨城県,2564,177,78,39,74,409,518,419,289,141,90,73,76,62,29,31,17,13,16,13,Both,2010,01
9,09,栃木県,1686,102,45,32,49,304,355,226,166,120,60,56,51,49,26,14,12,11,5,3,Both,2010,01
10,10,群馬県,1509,95,36,23,36,244,308,234,164,105,66,59,44,40,13,14,7,7,8,6,Both,2010,01
11,11,埼玉県,8657,523,208,130,201,1221,1954,1429,1012,501,335,272,265,248,123,72,57,44,45,17,Both,2010,01
12,12,千葉県,7771,485,191,101,181,1087,1783,1384,866,447,260,215,213,231,129,51,46,43,41,17,Both,2010,01
13,13,東京都,21182,1122,371,169,374,2875,5003,3727,2370,1430,813,643,582,618,344,238,166,168,97,72,Both,2010,01
14,14,神奈川県,11664,715,267,133,238,1554,2658,2044,1319,764,473,302,349,328,192,109,81,68,50,20,Both,2010,01
15,15,新潟県,1293,68,33,15,47,306,261,181,129,79,46,31,36,19,8,4,9,12,4,5,Both,2010,01
16,16,富山県,674,33,23,10,21,129,115,102,64,56,33,27,21,16,4,6,6,5,2,1,Both,2010,01
17,17,石川県,881,66,31,14,44,145,174,136,83,60,35,32,25,16,7,3,5,2,3,0,Both,2010,01
18,18,福井県,520,35,21,5,18,99,92,65,63,36,20,19,11,10,6,5,6,4,2,3,Both,2010,01
19,19,山梨県,814,40,20,18,76,180,157,99,69,36,25,26,13,18,10,5,6,10,1,5,Both,2010,01

In [15]:
keys_3xls = ['Total', '0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74', '75-79', '80-84', '85-89', '90 & above']
in_melted_df = pd.melt(in_migrants_age_df, 
                       id_vars=['Prefecture Num', 'Prefecture', 'Gender', 'Year', 'Month'], 
                       value_name='Inmigrants', 
                       value_vars=keys_3xls, 
                       var_name='Age bucket')
out_melted_df = pd.melt(out_migrants_age_df, 
                        id_vars=['Prefecture Num', 'Prefecture', 'Gender', 'Year', 'Month'], 
                        value_name='Outmigrants', 
                        value_vars=keys_3xls, 
                        var_name='Age bucket')

In [16]:
combined_melted_df = pd.merge(in_melted_df, out_melted_df, how='left',
                              left_on=list(in_melted_df.columns).remove('Inmigrants'), 
                              right_on=list(out_melted_df.columns).remove('Outmigrants'))

In [17]:
len(combined_melted_df)

293760

In [18]:
out_melted_df.shape[0] == combined_melted_df.shape[0]

True

In [19]:
shared_columns = [x for x in list(internal_melted_df.columns) if x in list(combined_melted_df.columns)]
final_combined_melted_df = pd.merge(combined_melted_df, internal_melted_df, how='outer',
                              left_on=shared_columns, 
                              right_on=shared_columns)

In [20]:
len(final_combined_melted_df)

310032

In [21]:
final_combined_melted_df['Prefecture_English'] = final_combined_melted_df.apply(lambda x: jp2en_dict.get(x['Prefecture']), axis=1)

In [22]:
abcdf = pd.DataFrame(final_combined_melted_df.isnull().sum())
logging.info(tabulate(abcdf, headers='keys', tablefmt='psql'))

INFO:root:+--------------------+--------+
|                    |      0 |
|--------------------+--------|
| Prefecture Num     |      0 |
| Prefecture         |      0 |
| Gender             |      0 |
| Year               |      0 |
| Month              |      0 |
| Age bucket         |      0 |
| Inmigrants         |  16272 |
| Outmigrants        |  16272 |
| Prefecture_English |      0 |
| Internal migrants  | 279072 |
+--------------------+--------+

About 30 months of major city and metropolitan area internal migration data for which there is no corresponding in/out migration data.

Internal migration data only available for total population of each gender, not each age bracket.

In [23]:
final_combined_melted_df.tail(30)

,Prefecture Num,Prefecture,Gender,Year,Month,Age bucket,Inmigrants,Outmigrants,Prefecture_English,Internal migrants
310002,33 100,岡山市,Female,2018,05,Total,NaN,NaN,Okayama-shi,419
310003,34 100,広島市,Female,2018,05,Total,NaN,NaN,Hiroshima-shi,1028
310004,40 100,北九州市,Female,2018,05,Total,NaN,NaN,Kitakyushu-shi,652
310005,40 130,福岡市,Female,2018,05,Total,NaN,NaN,Fukuoka-shi,1599
310006,43 100,熊本市,Female,2018,05,Total,NaN,NaN,Kumamoto-shi,755
310007,100,東京圏,Female,2018,06,Total,NaN,NaN,Tokyo Area,44952
310008,101,名古屋圏,Female,2018,06,Total,NaN,NaN,Nagoya Area,8681
310009,102,大阪圏,Female,2018,06,Total,NaN,NaN,Osaka Area,16957
310010,00 000,21 大 都 市 計,Female,2018,06,Total,NaN,NaN,Total of 21 major cities,27215
310011,01 100,札幌市,Female,2018,06,Total,NaN,NaN,Sapporo-shi,2282
310012,04 100,仙台市,Female,2018,06,Total,NaN,NaN,Sendai-shi,795
310013,11 100,さいたま市,Female,2018,06,Total,NaN,NaN,Saitama-shi,673
310014,12 100,千葉市,Female,2018,06,Total,NaN,NaN,Chiba-shi,418
310015,13 100,東京都特別区部,Female,2018,06,Total,NaN,NaN,Ku-area of Tokyo,8829
310016,14 100,横浜市,Female,2018,06,Total,NaN,NaN,Yokohama-shi,2507
310017,14 130,川崎市,Female,2018,06,Total,NaN,NaN,Kawasaki-shi,605
310018,14 150,相模原市,Female,2018,06,Total,NaN,NaN,Sagamihara-shi,194
310019,15 100,新潟市,Female,2018,06,Total,NaN,NaN,Niigata-shi,426
310020,22 100,静岡市,Female,2018,06,Total,NaN,NaN,Shizuoka-shi,268
310021,22 130,浜松市,Female,2018,06,Total,NaN,NaN,Hamamatsu-shi,487
310022,23 100,名古屋市,Female,2018,06,Total,NaN,NaN,Nagoya-shi,1752
310023,26 100,京都市,Female,2018,06,Total,NaN,NaN,Kyoto-shi,924
310024,27 100,大阪市,Female,2018,06,Total,NaN,NaN,Osaka-shi,2213
310025,27 140,堺市,Female,2018,06,Total,NaN,NaN,Sakai-shi,361
310026,28 100,神戸市,Female,2018,06,Total,NaN,NaN,Kobe-shi,884
310027,33 100,岡山市,Female,2018,06,Total,NaN,NaN,Okayama-shi,348
310028,34 100,広島市,Female,2018,06,Total,NaN,NaN,Hiroshima-shi,796
310029,40 100,北九州市,Female,2018,06,Total,NaN,NaN,Kitakyushu-shi,548
310030,40 130,福岡市,Female,2018,06,Total,NaN,NaN,Fukuoka-shi,1316
310031,43 100,熊本市,Female,2018,06,Total,NaN,NaN,Kumamoto-shi,589

In [ ]:
def dataframe_to_postgres(df, tablename):
    cur = conn.cursor()
    textstream = io.StringIO()
    upload_df = df.copy()
    #upload_df['excel_description'].replace(['\n', '\t'], '', regex=True, inplace=True)

    upload_df.to_csv(textstream, sep='\t', header=False, index=False, quoting=csv.QUOTE_NONE)
    textstream.seek(0) 
    cur.copy_from(textstream, tablename, null="") # null values become ''
    conn.commit()

In [24]:
table_2_list= [x for x in filepathlist if x.split('\\')[-1] == '2.xls']

In [25]:
filepath = table_2_list[0]
print(filepath)

sheets = pd.ExcelFile(filepath).sheet_names
df = pd.read_excel(filepath, sheet_name=len(sheets)-1)

messy_df = df.copy()
messy_df.reset_index(inplace=True)

cornerstone = 'Origin'
cornerstone_col_idx = [messy_df.columns.get_loc(x) for x in messy_df.columns if cornerstone in messy_df[x].values][0]
cornerstone_col = messy_df.iloc[:,cornerstone_col_idx]
cornerstone_row_idx_list = [x - 2 for x in list(cornerstone_col.index[cornerstone_col == cornerstone])]
terminal_row_idx_list = [messy_df.iloc[cornerstone:][messy_df.isnull().all(axis=1)].reset_index()['index'][1] for cornerstone in cornerstone_row_idx_list]

start_end_rows_idx_list = list(zip(cornerstone_row_idx_list, terminal_row_idx_list))
trajectory_df_list = []
for idx, row_idx in enumerate(start_end_rows_idx_list):
    start = row_idx[0]
    end = row_idx[1]
    df = messy_df.copy()
    df = df.iloc[start:end,cornerstone_col_idx:]
    df.dropna(thresh=len(df)-10, axis=1, inplace=True)
    df.dropna(how='all', axis=0, inplace=True)
    df.iloc[:,0] = df.apply(lambda x: x.iloc[1] if str(x.iloc[0]).isnumeric() else x.iloc[0], axis=1) #shift row names to col 0
    df.dropna(thresh=len(df)-4, axis=1, inplace=True)
    df.ffill(axis=1, inplace=True)
    df = df[~df.iloc[:,0].str.contains('Origin', na=False)].iloc[1:,:] #remove the rows with kanji headers
    df.fillna('Origin', inplace=True)
    df.replace('-', np.nan, inplace=True)
    df.replace('Both sexes', 'Both', inplace=True)
    df.set_index(df.columns[0], inplace=True)
    
    location_header = list(df.iloc[0,:].unique())
    gender_header = list(df.iloc[1,:].unique())
    header = pd.MultiIndex.from_product([location_header, gender_header])
    df.columns = header
    df.index = [x.rstrip(' 1)') for x in list(df.index)]
    df = df.iloc[2:]
    melted_partial_trajectories_df = pd.melt(df.reset_index(), 
                                             id_vars='index', 
                                             value_name='Migrants', 
                                             var_name=['Destination', 'Gender'])
    
    trajectory_df_list.append(melted_partial_trajectories_df)

combined_melted_trajectories_df = pd.concat(trajectory_df_list, axis=0)
combined_melted_trajectories_df.rename(columns = {'index': 'Origin'}, inplace=True)
combined_melted_trajectories_df.reset_index(drop=True, inplace=True)

C:\Users\friedemann.ang\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  # This is added back by InteractiveShellApp.init_path()
C:\Users\friedemann.ang\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

extracts\monthly_reports\2006\01Jan\2.xls

In [26]:
combined_melted_trajectories_df.shape

(12480, 4)